STF: stf::process_invalid
void stf::process_invalid (unit::env & env, std::ptrdiff_t count) inline
#include <stf/unit/env.hpp>
Handle the case of invalid scenario, i.e test case with no test inside.
Parameters
env Environment to use as data source
count Expected number of test to have run
References stf::unit::env::as_invalid(), stf::unit::env::invalid(), stf::unit::env::is_compact(), stf::unit::env::stream(), and stf::unit::env::tests().
Referenced by stf::run().