STF: stf::run
template<typename Environment , typename Suite , typename... Setup> bool stf::run (Environment & environment, Suite & tests, Setup const &... setup) inline
#include <stf/common/driver.hpp>
Starts the execution of a group of function object.
Starts the execution of every functions registered as a test suite of any kind and report success or failure with respect to the expectation of said test semantic.
Usually, the test suite being run is given by stf::test_suite() but it can differs in some use case, hence the need to pass it as a parameter.
Example:
int main(int argc, char** argv)
{
  ::stf::env $env(std::cout);
  // Test specific setup goes here
  auto result = ::stf::run( $env, ::stf::suite(), {0,0} );
  // Test specific clean-up goes here
  return result;
}
Parameters
environment Test environment
tests Test suite to execute
setup Additional, test kind specific, parameters
Returns
A boolean value indicating if the whole test is considered a success.
References stf::args, stf::process_invalid(), stf::report(), and stf::scenario_header().